package club.tushar.tourplancost.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import club.tushar.tourplancost.db.Tour;
import club.tushar.tourplancost.db.TourEventCost;

import club.tushar.tourplancost.db.TourDao;
import club.tushar.tourplancost.db.TourEventCostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tourDaoConfig;
    private final DaoConfig tourEventCostDaoConfig;

    private final TourDao tourDao;
    private final TourEventCostDao tourEventCostDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tourDaoConfig = daoConfigMap.get(TourDao.class).clone();
        tourDaoConfig.initIdentityScope(type);

        tourEventCostDaoConfig = daoConfigMap.get(TourEventCostDao.class).clone();
        tourEventCostDaoConfig.initIdentityScope(type);

        tourDao = new TourDao(tourDaoConfig, this);
        tourEventCostDao = new TourEventCostDao(tourEventCostDaoConfig, this);

        registerDao(Tour.class, tourDao);
        registerDao(TourEventCost.class, tourEventCostDao);
    }
    
    public void clear() {
        tourDaoConfig.clearIdentityScope();
        tourEventCostDaoConfig.clearIdentityScope();
    }

    public TourDao getTourDao() {
        return tourDao;
    }

    public TourEventCostDao getTourEventCostDao() {
        return tourEventCostDao;
    }

}
