package club.tushar.tourplancost.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TOUR".
 */
@Entity
public class Tour {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private String name;
    private Long startDate;
    private Long endDate;
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Tour() {
    }

    public Tour(Long id) {
        this.id = id;
    }

    @Generated
    public Tour(Long id, String name, Long startDate, Long endDate, String description) {
        this.id = id;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getStartDate() {
        return startDate;
    }

    public void setStartDate(Long startDate) {
        this.startDate = startDate;
    }

    public Long getEndDate() {
        return endDate;
    }

    public void setEndDate(Long endDate) {
        this.endDate = endDate;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
