package club.tushar.tourplancost.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TOUR_EVENT_COST".
 */
@Entity
public class TourEventCost {

    @Id(autoincrement = true)
    private Long id;
    private Long tourId;
    private String name;
    private Long Date;
    private Integer cost;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TourEventCost() {
    }

    public TourEventCost(Long id) {
        this.id = id;
    }

    @Generated
    public TourEventCost(Long id, Long tourId, String name, Long Date, Integer cost) {
        this.id = id;
        this.tourId = tourId;
        this.name = name;
        this.Date = Date;
        this.cost = cost;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTourId() {
        return tourId;
    }

    public void setTourId(Long tourId) {
        this.tourId = tourId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getDate() {
        return Date;
    }

    public void setDate(Long Date) {
        this.Date = Date;
    }

    public Integer getCost() {
        return cost;
    }

    public void setCost(Integer cost) {
        this.cost = cost;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
