package club.tushar.tourplancost.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TOUR_EVENT_COST".
 */
@Entity
public class TourEventCost {

    @Id(autoincrement = true)
    private Long id;
    private Long tourId;
    private String eventName;
    private Long date;
    private Integer cost;
    private Boolean synced;
    private Boolean isSelected;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TourEventCost() {
    }

    public TourEventCost(Long id) {
        this.id = id;
    }

    @Generated
    public TourEventCost(Long id, Long tourId, String eventName, Long date, Integer cost, Boolean synced, Boolean isSelected) {
        this.id = id;
        this.tourId = tourId;
        this.eventName = eventName;
        this.date = date;
        this.cost = cost;
        this.synced = synced;
        this.isSelected = isSelected;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTourId() {
        return tourId;
    }

    public void setTourId(Long tourId) {
        this.tourId = tourId;
    }

    public String getEventName() {
        return eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public Integer getCost() {
        return cost;
    }

    public void setCost(Integer cost) {
        this.cost = cost;
    }

    public Boolean getSynced() {
        return synced;
    }

    public void setSynced(Boolean synced) {
        this.synced = synced;
    }

    public Boolean getIsSelected() {
        return isSelected;
    }

    public void setIsSelected(Boolean isSelected) {
        this.isSelected = isSelected;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
